/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaRecetas.Ventanas;

import static SistemaRecetas.Ventanas.Home.etiquetas;
import java.util.ArrayList;

/**
 *
 * @author Edgar Murillo
 */
public class EditarReceta extends javax.swing.JFrame {
    public static String ingredienteSeleccionado;
    
    /**
     * Creates new form Home
     */
    public EditarReceta() {
        initComponents();
        etiquetas = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditarReceta = new javax.swing.JPanel();
        spinnerTiempo = new javax.swing.JSpinner();
        labelUtensilios = new javax.swing.JLabel();
        PanelIngredientes = new javax.swing.JPanel();
        labelIngredientes = new javax.swing.JLabel();
        panelListaUtensilios = new javax.swing.JScrollPane();
        listaUtensilios = new javax.swing.JList<>();
        textoPorciones = new javax.swing.JTextField();
        panelListaIngredientes = new javax.swing.JScrollPane();
        listaIngredientes1 = new javax.swing.JList<>();
        Back4 = new javax.swing.JLabel();
        labelPorciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textoNombre = new javax.swing.JTextField();
        labelTiempo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelDificultad = new javax.swing.JLabel();
        comboDificultad = new javax.swing.JComboBox<>();
        AlacenaBg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EditorRecetas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //EditarReceta.setVisible(false);
        EditarReceta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        EditarReceta.add(spinnerTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 170, -1));

        labelUtensilios.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        labelUtensilios.setForeground(new java.awt.Color(84, 62, 42));
        labelUtensilios.setText("Utensilios");
        EditarReceta.add(labelUtensilios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 100, 30));

        PanelIngredientes.setOpaque(false);
        PanelIngredientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIngredientes.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        labelIngredientes.setForeground(new java.awt.Color(84, 62, 42));
        labelIngredientes.setText("Ingredientes");
        PanelIngredientes.add(labelIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        listaUtensilios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Ingrediente 1", "Ingrediente 2", "Ingrediente 3"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaUtensilios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaUtensiliosMousePressed(evt);
            }
        });
        panelListaUtensilios.setViewportView(listaUtensilios);

        PanelIngredientes.add(panelListaUtensilios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, 140));

        EditarReceta.add(PanelIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 340, 190));

        textoPorciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPorcionesActionPerformed(evt);
            }
        });
        EditarReceta.add(textoPorciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 180, 20));

        listaIngredientes1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Ingrediente 1", "Ingrediente 2", "Ingrediente 3"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaIngredientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaIngredientes1MousePressed(evt);
            }
        });
        panelListaIngredientes.setViewportView(listaIngredientes1);

        EditarReceta.add(panelListaIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 330, 150));

        Back4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        Back4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back4MousePressed(evt);
            }
        });
        EditarReceta.add(Back4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 60, 40));

        labelPorciones.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        labelPorciones.setForeground(new java.awt.Color(84, 62, 42));
        labelPorciones.setText("Porciones");
        EditarReceta.add(labelPorciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 80, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        EditarReceta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 480, 330));

        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });
        EditarReceta.add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 20));

        labelTiempo.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        labelTiempo.setForeground(new java.awt.Color(84, 62, 42));
        labelTiempo.setText("Tiempo");
        EditarReceta.add(labelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 150, 30));

        labelNombre.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(84, 62, 42));
        labelNombre.setText("Nombre");
        EditarReceta.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 30));

        labelDificultad.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        labelDificultad.setForeground(new java.awt.Color(84, 62, 42));
        labelDificultad.setText("Dificultad");
        EditarReceta.add(labelDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 170, 30));

        comboDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil" }));
        EditarReceta.add(comboDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 170, -1));

        AlacenaBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EditarReceta.png"))); // NOI18N
        EditarReceta.add(AlacenaBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(EditarReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoPorcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPorcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPorcionesActionPerformed

    private void listaIngredientes1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaIngredientes1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaIngredientes1MousePressed

    private void Back4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back4MousePressed
        this.dispose();
    }//GEN-LAST:event_Back4MousePressed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void listaUtensiliosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUtensiliosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaUtensiliosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarReceta().setVisible(true);
            }
        });
    }
/*    
    // FUNCION PARA EDITAR EL MENU DE ETIQUETAS:
    public void cambiarEtiquetas(String[] etiquetas)
    {
        ComboEtiquetas.setModel(new javax.swing.DefaultComboBoxModel<>(etiquetas));
    }
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlacenaBg2;
    private javax.swing.JLabel Back4;
    private javax.swing.JPanel EditarReceta;
    private javax.swing.JPanel PanelIngredientes;
    private javax.swing.JComboBox<String> comboDificultad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelDificultad;
    private javax.swing.JLabel labelIngredientes;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPorciones;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JLabel labelUtensilios;
    private javax.swing.JList<String> listaIngredientes1;
    private javax.swing.JList<String> listaUtensilios;
    private javax.swing.JScrollPane panelListaIngredientes;
    private javax.swing.JScrollPane panelListaUtensilios;
    private javax.swing.JSpinner spinnerTiempo;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoPorciones;
    // End of variables declaration//GEN-END:variables
}
