/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaRecetas.Ventanas;

import SistemaRecetas.*;
import SistemaRecetas.GUIControllerSingleton;
import static SistemaRecetas.SistemaRecetas.guiController;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Home extends javax.swing.JFrame {
    
    // listas
    public static ArrayList<Etiqueta> etiquetas; 
    private static ArrayList<Utensilio> utensilios; 
    private static ArrayList<Ingrediente> ingredientes; 
    private static ArrayList<Receta> recetas;
    
    // Variables ventana "Alacena"
    private static String ingredienteSeleccionado;
    private GUIControllerSingleton controller;
    
    
    
    /**
     * Creates new form Home
     */
   public Home() throws IOException  {        
        controller = GUIControllerSingleton.getInstance();
        
        etiquetas = controller.getEtiquetas();
        utensilios = controller.getUtensilios();
        ingredientes = controller.getIngredientes();
        recetas = controller.getRecetas();
        
        setFont();
        centreWindow(this);
        initComponents();
        Comer.setVisible(false);
        Recetas.setVisible(false);
        Alacena.setVisible(false);
        Utensilios.setVisible(false);
    }
   
   public void setEtiquetas (ArrayList<Etiqueta> etiquetas)
   {
       System.out.println("Harambe is bae!");
       Home.etiquetas = etiquetas;
   }
   
   public void setIngredientes (ArrayList<Ingrediente> ingredientes)
   {
       Home.ingredientes = ingredientes;
   }
   
   public void setUtensilios (ArrayList<Utensilio> utensilios)
   {
       Home.utensilios = utensilios;
   }
   
   public void setRecetas (ArrayList<Receta> recetas)
   {
       Home.recetas = recetas;
   }
   
   public void actualizarEtiquetas()
   {
       ArrayList<String> nombres = new ArrayList<>();
        if (etiquetas != null)
        {
            for (Etiqueta etiqueta : etiquetas)
            {
                nombres.add(etiqueta.getNombre());
            }
        }

        String[] stockArr = new String[nombres.size()];
        stockArr = nombres.toArray(stockArr);
        comboEtiquetas.setModel(new javax.swing.DefaultComboBoxModel<>(stockArr));
   }
   
   public void setFont() throws IOException {
       try {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("GrandHotel-Regular.otf")));
       } catch (FontFormatException e) {
            System.out.println(e.getMessage());
            //Handle exception
       }
       
   }
   public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 3);
        int y = (int) (5);
        frame.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonComer = new javax.swing.JButton();
        botonRecetas = new javax.swing.JButton();
        botonAlacena = new javax.swing.JButton();
        botonUtensilios = new javax.swing.JButton();
        mainWindow = new javax.swing.JLabel();
        Recetas = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRecetas = new javax.swing.JList<>();
        AgregarReceta = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        BorrarReceta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ventanaRecetas = new javax.swing.JLabel();
        Comer = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        Dificultad = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        comboEtiquetas = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        Back1 = new javax.swing.JLabel();
        ventanaRecetas1 = new javax.swing.JLabel();
        Alacena = new javax.swing.JPanel();
        AlacenaHome = new javax.swing.JPanel();
        Ingredientes = new javax.swing.JScrollPane();
        listaIngredientes = new javax.swing.JList<>();
        Back2 = new javax.swing.JLabel();
        AgregarIgrediente = new javax.swing.JLabel();
        AlacenaBg2 = new javax.swing.JLabel();
        editarIngredientes = new javax.swing.JPanel();
        editIngre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Back4 = new javax.swing.JLabel();
        AlacenaBg = new javax.swing.JLabel();
        Utensilios = new javax.swing.JPanel();
        Back3 = new javax.swing.JLabel();
        AlacenaBg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nacho's");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setFont(new java.awt.Font("Grand Hotel", 0, 11)); // NOI18N
        jPanel2.setOpaque(false);

        botonComer.setFont(new java.awt.Font("Grand Hotel", 0, 40)); // NOI18N
        botonComer.setForeground(new java.awt.Color(84, 62, 42));
        botonComer.setText("¿Qué comemos?");
        botonComer.setAlignmentY(0.0F);
        botonComer.setBorderPainted(false);
        botonComer.setContentAreaFilled(false);
        botonComer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonComer.setFocusPainted(false);
        botonComer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonComerMousePressed(evt);
            }
        });
        botonComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComerActionPerformed(evt);
            }
        });

        botonRecetas.setFont(new java.awt.Font("Grand Hotel", 0, 40)); // NOI18N
        botonRecetas.setForeground(new java.awt.Color(84, 62, 42));
        botonRecetas.setText("Recetas");
        botonRecetas.setBorderPainted(false);
        botonRecetas.setContentAreaFilled(false);
        botonRecetas.setFocusPainted(false);
        botonRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecetasActionPerformed(evt);
            }
        });

        botonAlacena.setFont(new java.awt.Font("Grand Hotel", 0, 40)); // NOI18N
        botonAlacena.setForeground(new java.awt.Color(84, 62, 42));
        botonAlacena.setText("Alacena");
        botonAlacena.setBorderPainted(false);
        botonAlacena.setContentAreaFilled(false);
        botonAlacena.setFocusPainted(false);
        botonAlacena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAlacenaMousePressed(evt);
            }
        });

        botonUtensilios.setFont(new java.awt.Font("Grand Hotel", 0, 40)); // NOI18N
        botonUtensilios.setForeground(new java.awt.Color(84, 62, 42));
        botonUtensilios.setText("Utensilios");
        botonUtensilios.setBorderPainted(false);
        botonUtensilios.setContentAreaFilled(false);
        botonUtensilios.setFocusPainted(false);
        botonUtensilios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonUtensiliosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAlacena)
                    .addComponent(botonRecetas)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonComer))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(botonUtensilios))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonComer)
                .addGap(18, 18, 18)
                .addComponent(botonRecetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonAlacena)
                .addGap(18, 18, 18)
                .addComponent(botonUtensilios)
                .addContainerGap())
        );

        mainWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MainWindow.png"))); // NOI18N

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainWindow)))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainWindow))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(HomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaRecetas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "yea", "boi", "mom", "spaguetti", "harambe", "dick" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaRecetas);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 280, 360));

        AgregarReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        AgregarReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarRecetaMousePressed(evt);
            }
        });
        jLayeredPane1.add(AgregarReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, 40));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
        });
        jLayeredPane1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 60, 40));

        BorrarReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        BorrarReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BorrarRecetaMousePressed(evt);
            }
        });
        jLayeredPane1.add(BorrarReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 50, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit(1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 60, 60));

        ventanaRecetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentanaRecetas.png"))); // NOI18N
        jLayeredPane1.add(ventanaRecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout RecetasLayout = new javax.swing.GroupLayout(Recetas);
        Recetas.setLayout(RecetasLayout);
        RecetasLayout.setHorizontalGroup(
            RecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecetasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RecetasLayout.setVerticalGroup(
            RecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecetasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Recetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dificultad.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        Dificultad.setForeground(new java.awt.Color(84, 62, 42));
        Dificultad.setText("Dificultad");
        Dificultad.setContentAreaFilled(false);
        Dificultad.setFocusPainted(false);
        Dificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DificultadActionPerformed(evt);
            }
        });
        jLayeredPane3.add(Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(84, 62, 42));
        jCheckBox4.setText("Duración");
        jCheckBox4.setContentAreaFilled(false);
        jCheckBox4.setFocusPainted(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(84, 62, 42));
        jCheckBox3.setText("Etiqueta");
        jCheckBox3.setContentAreaFilled(false);
        jCheckBox3.setFocusPainted(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        ArrayList<String> nombres = new ArrayList<>();
        if (etiquetas != null)
        {
            for (Etiqueta etiqueta : etiquetas)
            {
                nombres.add(etiqueta.getNombre());
            }
        }

        String[] stockArr = new String[nombres.size()];
        stockArr = nombres.toArray(stockArr);
        comboEtiquetas.setModel(new javax.swing.DefaultComboBoxModel<>(stockArr));
        comboEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEtiquetasActionPerformed(evt);
            }
        });
        jLayeredPane3.add(comboEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 120, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-30min", "30-60min", "60+min" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 120, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Medio", "Difícil", "Experto" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, -1));

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 62, 42));
        jLabel2.setText("Recetas");

        jList2.setBackground(new java.awt.Color(246, 170, 53));
        jList2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList2.setForeground(new java.awt.Color(84, 62, 42));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jList2);

        jLabel3.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(84, 62, 42));
        jLabel3.setText("En Alacena");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jLayeredPane3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 280, 170));

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back1MousePressed(evt);
            }
        });
        jLayeredPane3.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 60, 40));

        ventanaRecetas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentanaComer.png"))); // NOI18N
        jLayeredPane3.add(ventanaRecetas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout ComerLayout = new javax.swing.GroupLayout(Comer);
        Comer.setLayout(ComerLayout);
        ComerLayout.setHorizontalGroup(
            ComerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ComerLayout.setVerticalGroup(
            ComerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Comer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AlacenaHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaIngredientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "hola", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaIngredientesMousePressed(evt);
            }
        });
        Ingredientes.setViewportView(listaIngredientes);

        AlacenaHome.add(Ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 280, 360));

        Back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        Back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back2MousePressed(evt);
            }
        });
        AlacenaHome.add(Back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 60, 40));

        AgregarIgrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        AgregarIgrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarIgredienteMousePressed(evt);
            }
        });
        AlacenaHome.add(AgregarIgrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, 40));

        AlacenaBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentanaAlacena.png"))); // NOI18N
        AlacenaHome.add(AlacenaBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        editarIngredientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editIngre.setFont(new java.awt.Font("Grand Hotel", 0, 24)); // NOI18N
        editIngre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        editIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editIngreActionPerformed(evt);
            }
        });
        editarIngredientes.add(editIngre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 220, 50));

        jLabel4.setText("Editar Ingrediente");
        editarIngredientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 140, 30));

        Back4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        Back4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back4MousePressed(evt);
            }
        });
        editarIngredientes.add(Back4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 60, 40));

        AlacenaBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentanaAlacena.png"))); // NOI18N
        editarIngredientes.add(AlacenaBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout AlacenaLayout = new javax.swing.GroupLayout(Alacena);
        Alacena.setLayout(AlacenaLayout);
        AlacenaLayout.setHorizontalGroup(
            AlacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AlacenaHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(editarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AlacenaLayout.setVerticalGroup(
            AlacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AlacenaHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(editarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(Alacena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Utensilios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        Back3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Back3MousePressed(evt);
            }
        });
        Utensilios.add(Back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 60, 40));

        AlacenaBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VentanaUtensilios.png"))); // NOI18N
        Utensilios.add(AlacenaBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Utensilios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecetasActionPerformed
           // TODO add your handling code here:
        Recetas.setVisible(true);
        this.setContentPane(Recetas);
        this.invalidate();
        this.validate();
    }//GEN-LAST:event_botonRecetasActionPerformed

    private void DificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DificultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DificultadActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void comboEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEtiquetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEtiquetasActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        Comer.setVisible(false);
        Recetas.setVisible(false);
        Alacena.setVisible(false);
        Utensilios.setVisible(false);
        this.setContentPane(HomePanel);
        this.invalidate();
        this.validate();
    }//GEN-LAST:event_BackMousePressed

    private void Back1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MousePressed
       Comer.setVisible(false);
       Recetas.setVisible(false);
       Alacena.setVisible(false);
       Utensilios.setVisible(false);
       this.setContentPane(HomePanel);
       this.invalidate();
       this.validate();
    }//GEN-LAST:event_Back1MousePressed

    private void Back2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back2MousePressed
      Comer.setVisible(false);
      Recetas.setVisible(false);
      Alacena.setVisible(false);
      Utensilios.setVisible(false);
      this.setContentPane(HomePanel);
      this.invalidate();
      this.validate();
    }//GEN-LAST:event_Back2MousePressed

    private void Back3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back3MousePressed
      Comer.setVisible(false);
      Recetas.setVisible(false);
      Alacena.setVisible(false);
      Utensilios.setVisible(false);
      this.setContentPane(HomePanel);
      this.invalidate();
      this.validate();
    }//GEN-LAST:event_Back3MousePressed

    private void botonUtensiliosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUtensiliosMousePressed
      Utensilios.setVisible(true);
      this.setContentPane(Utensilios);
      this.invalidate();
      this.validate();
    }//GEN-LAST:event_botonUtensiliosMousePressed

    private void botonAlacenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAlacenaMousePressed
      Alacena.setVisible(true);
      this.setContentPane(AlacenaHome);
      this.invalidate();
      this.validate();
    }//GEN-LAST:event_botonAlacenaMousePressed

    private void botonComerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComerMousePressed
      Comer.setVisible(true);
      this.setContentPane(Comer);
      this.invalidate();
      this.validate();
    }//GEN-LAST:event_botonComerMousePressed

    private void botonComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComerActionPerformed
    
    private void seleccionarIngrediente()
    {
        ingredienteSeleccionado = listaIngredientes.getSelectedValue();
    }
    
    private void listaIngredientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaIngredientesMousePressed
        // TODO add your handling code here:
        seleccionarIngrediente();
    }//GEN-LAST:event_listaIngredientesMousePressed

    private void BorrarRecetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarRecetaMousePressed
       int index = listaRecetas.getSelectedIndex();
       System.out.println(index);
    }//GEN-LAST:event_BorrarRecetaMousePressed

    private void AgregarRecetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRecetaMousePressed
        EditarReceta a = controller.getVentanaRecetas();
        a.show();
    }//GEN-LAST:event_AgregarRecetaMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
       EditarReceta a = controller.getVentanaRecetas();
        a.show();
    }//GEN-LAST:event_jLabel1MousePressed

    private void AgregarIgredienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarIgredienteMousePressed
      if (listaIngredientes.getSelectedIndex()!=-1){
        this.setContentPane(editarIngredientes);
        editIngre.setText(ingredienteSeleccionado);
        this.invalidate();
        this.validate();
      }
    }//GEN-LAST:event_AgregarIgredienteMousePressed

    private void Back4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back4MousePressed
      this.setContentPane(AlacenaHome);
      this.invalidate();
      this.validate();
    }//GEN-LAST:event_Back4MousePressed

    private void editIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIngreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editIngreActionPerformed

    public ArrayList<Etiqueta> getEtiquetas(){
        return etiquetas;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarIgrediente;
    private javax.swing.JLabel AgregarReceta;
    private javax.swing.JPanel Alacena;
    private javax.swing.JLabel AlacenaBg;
    private javax.swing.JLabel AlacenaBg1;
    private javax.swing.JLabel AlacenaBg2;
    private javax.swing.JPanel AlacenaHome;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Back1;
    private javax.swing.JLabel Back2;
    private javax.swing.JLabel Back3;
    private javax.swing.JLabel Back4;
    private javax.swing.JLabel BorrarReceta;
    private javax.swing.JPanel Comer;
    private javax.swing.JCheckBox Dificultad;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JScrollPane Ingredientes;
    private javax.swing.JPanel Recetas;
    private javax.swing.JPanel Utensilios;
    private javax.swing.JButton botonAlacena;
    private javax.swing.JButton botonComer;
    private javax.swing.JButton botonRecetas;
    private javax.swing.JButton botonUtensilios;
    private javax.swing.JComboBox<String> comboEtiquetas;
    private javax.swing.JTextField editIngre;
    private javax.swing.JPanel editarIngredientes;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaIngredientes;
    private javax.swing.JList<String> listaRecetas;
    private javax.swing.JLabel mainWindow;
    private javax.swing.JLabel ventanaRecetas;
    private javax.swing.JLabel ventanaRecetas1;
    // End of variables declaration//GEN-END:variables
}
